---
- name: install bouncer
  become: true
  package:
    state: present
    name:
      - znc
- name: install systemd unit
  copy:
    src: znc.service
    dest: /etc/systemd/system/znc.service
    owner: root
    group: root
    mode: 0644
- name: enable systemd unit
  systemd:
    daemon_reload: yes
    name: znc.service
    enabled: yes
    state: started
- name: open firewall port
  become: true
  firewalld:
    permanent: yes
    immediate: yes
    port: "19107/tcp"
    state: enabled
