---
# Install rpmfusion repo support

- name: install rpmfusion repos
  become: true
  package: name=https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  with_items:
    - free
    - nonfree

- name: install rpmfusion content
  become: true
  package:
    state: present
    name:
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-nonfree
      - gstreamer1-plugins-ugly
