---
# This playbook runs all setup tasks on registered hosts

- name: Set up common configurations
  hosts: all
  roles:
    - common
    - { role: firewalld, when: ansible_distribution == 'CentOS' }

- name: Set up public machines
  hosts: public
  roles:
    - { role: alt-ssh, tags: ['alt-ssh'] }
    - { role: webserver, tags: ['webserver'] }
    - { role: drupal, tags: ['drupal'] }
    - { role: ircbouncer, tags: ['ircbouncer'] }

- name: Set up any of my home Linux systems
  hosts: private
  roles:
    - { role: webserver, tags: ['webserver'] }
    - { role: packaging, tags: ['packaging'] }
    - { role: design, tags: ['design'] }
    - { role: rpmfusion, tags: ['rpmfusion'] }
    - { role: home, tags: ['home'] }
    - { role: google-chrome, tags: ['google-chrome'] }

- name: Set up my work laptop
  hosts: worklaptop
  roles:
    - { role: workclient, tags: ['workclient'] }
    - { role: drupal, tags: ['drupal'] }

- name: Set up workstations
  hosts: workstations
  roles:
    - { role: google-musicmanager, tags: ['google-musicmanager'] }
