---
# This playbook runs all setup tasks on registered hosts

- name: Set up common configurations
  hosts: all
  roles:
    - { role: firewalld, when: ansible_distribution == 'CentOS' }

- name: Set up public machines
  hosts: public
  roles:
    - { role: epel, tags: ['epel'] }
    - { role: remi, tags: ['remi'] }
    - { role: alt-ssh, tags: ['alt-ssh'] }
    - { role: webserver, tags: ['webserver'] }
    - { role: drupal, tags: ['drupal'] }
    - { role: ircbouncer, tags: ['ircbouncer'] }
    - { role: public-mailserver, tags: ['public-mailserver'] }

- name: Set up any of my home Linux systems
  hosts: private
  roles:
    - common
    - { role: webserver, tags: ['webserver'] }
    - { role: packaging, tags: ['packaging'] }
    - { role: design, tags: ['design'] }
    - { role: rpmfusion, tags: ['rpmfusion'] }
    - { role: home, tags: ['home'] }
    - { role: google-chrome, tags: ['google-chrome'] }

- name: Set up my work laptop
  hosts: worklaptop
  roles:
    - { role: workclient, tags: ['workclient'] }
    - { role: drupal, tags: ['drupal'] }

# - name: Set up workstations
#   hosts: workstations
#   roles:
#     - { role: google-musicmanager, tags: ['google-musicmanager'] }

- name: Set up scarlett
  hosts: scarlett
  roles:
    - {role: syslog-server, tags: ['syslog-server'] }
    - {role: office, tags: ['office'] }
