---
# This playbook runs all setup tasks on registered hosts

- name: Set up common configurations
  hosts: all
  roles:
    - common
    - { role: firewalld, when: ansible_distribution == 'CentOS' }

- name: Set up public machines
  hosts: public
  roles:
    - webserver
    - drupal

- name: Set up any of my home Linux systems
  hosts: private
  roles:
    - webserver
    - packaging
    - design
    - rpmfusion

- name: Set up my work laptop
  hosts: worklaptop
  roles:
    - workclient
