---
# Install Remi repo support

- name: install Remi repos
  become: true
  package:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
  when: ansible_distribution == "CentOS"
