---
- name: install common CLI utilities
  become: true
  package:
    state: present
    name:
      - tmux
      - tmux-powerline
      - powerline-fonts
      - pdfmerge
      - python3-ipython
- name: install tmux configuration
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    backup: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
- name: install powerline configuration
  copy:
    src: powerline-tmux.json
    dest: "{{ ansible_user_dir }}/.config/powerline/themes/tmux/config.json"
    backup: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
- name: install Emacs helpers
  become: true
  package:
    state: present
    name:
      - emacs-auto-complete
      - emacs-color-theme
      - emacs-gettext
      - emacs-magit
      - emacs-rpm-spec-mode
      - emacs-yaml-mode
- name: install graphical utilities
  become: true
  package:
    state: present
    name:
      - pavucontrol
      - gnome-tweak-tool
      - easytag
- name: install Microsoft pubkey
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: add VS Code yum repository
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
- name: install VS Code
  become: true
  dnf:
    name: code
    state: present
- name: enable SSH service
  become: true
  systemd:
    name: sshd.service
    state: started
    enabled: yes
