---
- name: install common CLI utilities
  become: true
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - tmuxinator
    - tmate
    - tmux-powerline
- name: install Emacs helpers
  become: true
  package: name={{ item }} state=latest
  with_items:
    - emacs-auto-complete
    - emacs-color-theme
    - emacs-gettext
    - emacs-magit
    - emacs-pymacs
    - emacs-rpm-spec-mode
    - emacs-yaml-mode
