---
- name: install common CLI utilities
  become: true
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - tmuxinator
    - tmate
    - tmux-powerline
    - powerline-fonts
    - pdfmerge
    - python-ipython
    - python3-ipython
    - python2-libselinux
    - python2-dbus
- name: install Emacs helpers
  become: true
  package: name={{ item }} state=latest
  with_items:
    - emacs-auto-complete
    - emacs-color-theme
    - emacs-gettext
    - emacs-magit
    - emacs-pymacs
    - emacs-rpm-spec-mode
    - emacs-yaml-mode
- name: install graphical utilities
  become: true
  package: name={{ item }} state=latest
  with_items:
    - pavucontrol
    - paprefs
    - gnome-tweak-tool
    - easytag
    - gobby05
- name: install Microsoft pubkey
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: add VS Code yum repository
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
- name: install VS Code
  become: true
  package:
    name: code
    state: latest
