---
- name: install common CLI utilities
  become: true
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - tmuxinator
    - tmate
    - tmux-powerline
    - powerline-fonts
    - pdfmerge
    - python-ipython
    - python3-ipython
- name: install Emacs helpers
  become: true
  package: name={{ item }} state=latest
  with_items:
    - emacs-auto-complete
    - emacs-color-theme
    - emacs-gettext
    - emacs-magit
    - emacs-pymacs
    - emacs-rpm-spec-mode
    - emacs-yaml-mode
- name: install graphical utilities
  become: true
  package: name={{ item }} state=latest
  with_items:
    - pavucontrol
    - paprefs
    - gnome-tweak-tool
    - Zim
    - easytag
    - gobby05

- include: "{{ ansible_fqdn }}.yml"
