---
- name: install graphics design tools
  become: true
  package: name={{ item }} state=latest
  with_items:
    - inkscape
    - gimp
    - xournal
    - gpick
    - ImageMagick

- name: install useful fonts
  become: true
  package: name={{ item }} state=latest
  with_items:
    - google-roboto-slab-fonts
    - julietaula-montserrat-fonts
    - typetype-molot-fonts
    - astigmatic-grand-hotel-fonts
    - overpass-fonts
  when: ansible_distribution == 'Fedora'
