---
- name: install work-related CLI utilities and libraries
  become: true
  package:
    state: present
    name:
      - task
      - hub
      - vagrant
      - vagrant-libvirt
      - python3-jira
      - python2-ansi2html
      - perl-HTML-Parser
      - openldap-clients
      - goobook
