---
- name: install indispensable packages
  become: true
  package: name={{ item }} state=latest
  with_items:
    - emacs-nox
    - git
    - avahi-tools
    - powertop
- name: enable powertop service
  become: true
  systemd:
    name: powertop.service
    enabled: yes
    state: started
- name: install authorized SSH key
  authorized_key:
    key: "https://pfrields.fedorapeople.org/configs/id_rsa.pub"
    state: present
    user: "{{ ansible_user }}"
