---
# Only install Drupal 7 core; manage modules locally
- name: install Drupal 7
  become: true
  package:
    state: present
    name:
      - drupal7
      - php
      - php-gd
      - php-mbstring

- include: "{{ ansible_distribution }}.yml"
